image: docker:18

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:18-dind

build:
  stage: build
  script:
    - apk --no-cache add openjdk14 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
    - ./mvnw clean install
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD rg.saaas.io
    - ./mvnw com.google.cloud.tools:jib-maven-plugin:build -Dimage=rg.saaas.io/4pjt/$CI_REGISTRY_IMAGE
    - ./mvnw com.google.cloud.tools:jib-maven-plugin:build -Dimage=rg.saaas.io/4pjt/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA