spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://${API_STORE_PG_URL}/dev"
    username: "postgres"
    password: "postgres"
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug
      hibernate:
        engine:
          jdbc:
            env:
              internal:
                LobCreatorBuilderImpl: error